; This file was auto-generated by drush_make
core = 6.x

projects[] = "drupal"
; Modules
projects[] = "admin"
projects[admin_menu][subdir] = "contrib"

projects[] = "backup_migrate"
projects[] = "content_access"
projects[date][subdir] = "date"

projects[] = "devel"
projects[] = "diff"
projects[] = "link"
projects[] = "markdown"
projects[] = "mollom"
projects[] = "pathauto"
projects[] = "poormanscron"
projects[] = "simplenews"
projects[] = "skinr"
projects[] = "switchtheme"
projects[] = "token"
projects[] = "views"
projects[] = "views_bulk_operations"
; Themes
projects[artistsC01][subdir] = "artistsC01-6.x-1.1/themes"

