; This file was auto-generated by drush_make
core = 6.x

projects[] = "drupal"
; Modules
projects[] = "addthis"
projects[] = "admin"
projects[] = "backup_migrate"
projects[] = "devel"
projects[] = "diff"
projects[] = "disqus"
projects[] = "markdown"
projects[] = "mollom"
projects[] = "pathauto"
projects[] = "poormanscron"
projects[] = "search404"
projects[] = "skinr"
projects[] = "storm"
projects[] = "switchtheme"
projects[] = "token"
projects[] = "twitter"
projects[] = "views"
; Themes
projects[] = "zen"
projects[] = "nitobe"
projects[] = "zeropoint"
projects[] = "zen_ninesixty"
